server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%t [%I] %{X-Forwarded-For}i %l %u %r %s %b %D"
      directory: logs/

###################  spring配置  ###################
spring:
  datasource:
    url: jdbc:mysql://localhost/maku?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: newsys
    driver-class-name: com.mysql.jdbc.Driver
  resources:
  jackson:
    time-zone: GMT+8

management:
  endpoints:
    web:
      exposure:
        include: "*"
